apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "smtp-transport"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
  annotations:
    texas.nais.io/enabled: "true"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "1024Mi"
  ingresses:
    - "https://smtp-transport.intern.nav.no"
  kafka:
    pool: nav-prod
  envFrom:
    - secret: smtp-transport-secrets
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvtokt
        mountPath: /secret/serviceuser
  accessPolicy:
    outbound:
      rules:
        - application: ebms-async
    inbound:
      rules:
        - application: ebms-async
  env:
    - name: SMTP_HOST
      value: "a30mxvl002.oera.no"
    - name: SMTP_PORT
      value: "25"
    - name: SMTP_POP3_FACTORY_PORT
      value: "110"
    - name: SMTP_POP3_PORT
      value: "110"
    - name: SMTP_POP3_HOST
      value: "a30mxvl002.oera.no"
    - name: SMTP_STORE_PROTOCOL
      value: "pop3"
    - name: SMTP_INCOMING_USERNAME
      value: "ebms-prod@es.nav.no"
#    - name: SMTP_REDIRECT_ADDRESS
#      value: "devnull@example.com"
    - name: SMTP_FROM_ADDRESS
      value: "mottak-prod@es.nav.no"
    - name: SMTP_T1_EMOTTAK_ADDRESS
      value: "mottak-a01wavl00008.adeo.no@es.nav.no"
    - name: POSTGRES_JDBC_URL
      value: "jdbc:postgresql://a01dbvl037.adeo.no:5432/emottak-smtp-transport-payload"
    - name: POSTGRES_MOUNT_PATH
      value: "postgresql/prod-fss"
    - name: POSTGRES_USER_ROLE
      value: "emottak-smtp-transport-payload-user"
    - name: POSTGRES_ADMIN_ROLE
      value: "emottak-smtp-transport-payload-admin"