apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "smtp-transport"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "1024Mi"
  ingresses:
    - "https://smtp-transport.intern.nav.no"
  envFrom:
    - secret: smtp-router-secrets
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvtokt
        mountPath: /secret/serviceuser
  accessPolicy:
    inbound:
      rules:
        - application: ebms-provider
  env:
    - name: SMTP_POP3_FACTORY_PORT
      value: "110"
    - name: SMTP_POP3_PORT
      value: "110"
    - name: SMTP_POP3_HOST
      value: "d32mxvl002.oera-t.local-not-in-use"
    - name: SMTP_STORE_PROTOCOL
      value: "pop3-not-in-use"
    - name: SMTP_INCOMING_USERNAME
      value: "nyebmstest@test-es.nav.no-not-in-use"
    - name: SMTP_BCC_USERNAME
      value: "nyebmsbcc@test-es.nav.no-not-in-use"
    - name: SMTP_OUTGOING_USERNAME_NY
      value: "nyebms2@test-es.nav.no-not-in-use"
    - name: DRY_RUN
      value: "true"
