ebmsFilter {
  typesToEbms = [
    "Inntektsforesporsel"
  ]
  typesToBoth = [
    "urn:oasis:names:tc:ebxml-msg:service",
  ]
  cpa = [
    "nav:119670",
    "nav:115510",
    "nav:63242",
    "nav:119530",
    "nav:115227",
    "nav:119189",
    "nav:63007",
    "nav:119191",
    "nav:119567",
    "nav:21723",
    "nav:117252",
    "nav:119671",
    "nav:114608",
    "nav:119528",
    "nav:119568"
  ]
}
