ebmsFilter {
  typesToEbms = [
    "Inntektsforesporsel",
    "Trekkopplysning"
  ]
  typesToBoth = [
    "urn:oasis:names:tc:ebxml-msg:service"
  ]
  cpaId = [
    "nav:qass:36666",
    "nav:qass:30500",
    "nav:qass:34961",
    "nav:qass:36181",
    "nav:qass:36221",
    "nav:qass:37969",
    "nav:qass:36584"
  ]
}
