# Hver tjeneste i lista skal rute meldinger til NYE Emottak.
# Tjenester som ikke er listet, vil rute meldinger til GAMLE Emottak.
#  mode="split" betyr at angitte meldinger (selection) rutes KUN til nye Emottak,
#  mode="both" betyr at angitte meldinger rutes BÅDE til nye og gamle Emottak.
# Utvalget av meldinger som skal rutes ihht mode, bestemmes av selection, whitelist og blacklist
#  selection="all" betyr at alle meldinger for tjenesten rutes ihht. mode
#  selection="percentageNN" betyr at NN prosent (heltall < 100) rutes ihht. mode, resten til gamle Emottak
#  selection="lastDigitN" betyr at CPA-IDer med sistesiffer lik N (kan angi flere) rutes ihht. mode, resten til gamle Emottak
#  selection="none" betyr at ingen CPA-IDer rutes ihht. mode. Brukes sammen med whitelist, eller for å dokumentere tjenester til gamle Emottak eksplisitt
# Alle konfigurasjoner må angi mode og selection.
#  Dersom blacklist er angitt, vil CPA-IDene i lista IKKE inkluderes, uansett selection-setting, disse rutes alltid til GAMLE Emottak
#  Dersom whitelist er angitt, vil CPA-IDene i lista ALLTID inkluderes, uansett selection-setting, disse rutes alltid til NYE Emottak
#  blacklist/whitelist peker på en tekstfil på classpath (innhold: en CPA-id per linje, # for kommentar)
services = [
  { name = "urn:oasis:names:tc:ebxml-msg:service", mode = "BOTH", selection = "all" },

  { name = "Inntektsforesporsel", mode = "split", selection = "all" },
  { name = "Trekkopplysning", mode = "split", selection = "all" },
  { name = "Sykmelding", mode = "split", selection = "all" },
  { name = "Legemelding", mode = "split", selection = "all" },
  { name = "HarBorgerFrikortMengde", mode = "split", selection = "all" },
  { name = "PasientlisteForesporsel", mode = "split", selection = "all" },

  #Isyfo
  { name = "DialogmoteInnkalling", mode = "BOTH", selection = "all" },
  { name = "ForesporselFraSaksbehandler", mode = "BOTH", selection = "all" },
  { name = "HenvendelseFraLege", mode = "BOTH", selection = "all" },
  { name = "HenvendelseFraSaksbehandler", mode = "BOTH", selection = "all" },
  { name = "Oppfolgingsplan", mode = "BOTH", selection = "all" },

  # helseref - KUHR
  { name = "BehandlerKrav", mode = "none", selection = "all" },
  { name = "S-KUHR_AKTIVITET", mode = "BOTH", selection = "all" },
  { name = "S-KUHR_KODEVERK", mode = "BOTH", selection = "all" },
  { name = "S-KUHR_PERSONIDENT", mode = "BOTH", selection = "all" },
  { name = "S-KUHR_SAMHANDLER", mode = "BOTH", selection = "all" },
  { name = "Sykdomspulsen", mode = "BOTH", selection = "all" },

  # Helseref - eresept
  { name = "Legemiddelinformasjon", mode = "BOTH", selection = "all" },
  { name = "OppgjorsKontroll", mode = "none", selection = "all" },
  { name = "Prisinformasjon", mode = "BOTH", selection = "all" }
]
