name: "Build and deploy smtp-transport to prod"
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  MODULE_NAME: "smtp-transport"
  NAIS_MANIFEST: "smtp-transport-prod.yaml"

jobs:
  build-and-push:
    name: "Build and push Docker container"
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
      repository-projects: write
      contents: write
      id-token: write
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-java@v4"
        with:
          java-version: 21
          distribution: temurin

      - name: "Cache gradle wrapper"
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: "Cache Gradle packages"
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-

      - name: "Build and tests ${{ env.MODULE_NAME }}"
        run: ./gradlew :test :build
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: team-emottak # required
          tag: ${{ github.sha }}
          dockerfile: Dockerfile # optional, default Dockerfile
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy:
    name: "Deploy to prod"
    needs: "build-and-push"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to PROD"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          CLUSTER: "prod-fss"
          RESOURCE: ".nais/${{ env.NAIS_MANIFEST }}"
          IMAGE: ${{ needs.build-and-push.outputs.image }}